# Generated by Django 2.2.7 on 2021-04-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
